[package]
name = "regen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "regen"
path = "src/main.rs"

[lib]
name = "regen"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
image = "0.25.6"
rand = "0.9.1"
tiled = "0.14.0"
