[package]
name = "tisu"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tisu"
path = "src/tisu.rs"

[lib]
name = "tisu"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rand = "0.9.1"
tiled = "0.14.0"
xml-rs = "0.8.26"
